ifdef CONFIG_NEBULA_DEBUG
obj-$(CONFIG_NEBULA_DEBUG) += nebula_debug_tools.o
obj-$(CONFIG_NEBULA_HELPER_FUNCTIONS) += helper_funcs.o
obj-$(CONFIG_NEBULA_REBOOT_BLOCK) += nebula_reboot_block.o
obj-$(CONFIG_NEBULA_DEBUG_RAMOOPS) += nebula_ramoops.o
obj-$(CONFIG_NEBULA_DEBUG_PAGE_USER_TRACE) += debug_page_user_trace.o
obj-$(CONFIG_NEBULA_DEBUG_BOOTLOADER_LOG) += nebula_bootloader_log.o
obj-$(CONFIG_NEBULA_NC_GPIO_PIN_SETTING)  += nebula_nc_setting.o
obj-$(CONFIG_NEBULA_DEBUG_SAVE_BOOT_MSG) += bootmsg.o
obj-$(CONFIG_NEBULA_PROCESS_DEBUG) += nebula_process_debug.o
obj-$(CONFIG_NEBULA_DEBUG_RESTART_TIMER) += nebula_restart_timer_notifier.o
endif
